print('|| soyez le bienvenue sur votre compte|| ')
n1=str(input('entrer votre nom: '))
n2=str(input('entrer votre prenom: '))
n3=str(input('entrer votre RIB bancaire: '))
arg=float(input('entrer votre argent que tu as dans votr compte: '))
print('votre information sont bien enregistrer :')
print('votre nom :'+str(n1))
print('votre prenom :'+str(n2))
print('votre RIB :'+str(n3))
print('votre argent actuel :'+str(arg))

print('|| le nom et le prenom de la personne que tu veux le verser largent||: ')
n4=str(input('entrer le nom: '))
n5=str(input('entrer le prenom: '))
n3=str(input('entrer son RIB bancaire: '))
n5=str(input('combien de largent tu veux le verser a ' +str(n4 + n5)))
n6=float(input('entrer largent : '))
print('|| votre compte bancaire: ' + str(n1 + n2))
print('votre donnee de votre compte :')
print('votre argent avant le versement cest: ' +str(arg))
print('votre argent apres le versement cest: ' +str(float(arg)-float(n6)))
